'version': '3'
'services':
  db-server:
    image: 'redis'
    restart: always
  web:
    build: .
    restart: always
    ports:
     - "3002:3001"
    volumes:
     - /usr/app/node_modules
     - .:/usr/app